projetoClinicaVeterinaria/ClinicaVeterinaria/ClinicaVeterinaria/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('',views.inicio, name="inicio"),
    path('Clinica', views.clinica, name="clinica"),
    path('editarClinica/<int:id>', views.editarClinica, name="editarClinica"),
    path('excluirClinica/<int:id>', views.excluirClinica, name="excluirClinica"),
    path('Cliente', views.cliente, name="cliente"),
    path('editarCliente/<int:id>', views.editarCliente, name="editarCliente"),
    path('excluirCliete/<int:id>', views.excluirCliente, name="excluirCliente"),
    path('Veterinario', views.veterinario, name="veterinario"),
    path('editarVeterinario/<int:id>/', views.editarVeterinario, name='editarVeterinario'),
    path('excluirVeterinario/<int:id>/', views.excluirVeterinario, name='excluirVeterinario'),
    path('pedido/', views.pedido, name="pedido"),
    path('editarPedido/<int:id>', views.editarPedido, name="editarPedido"),
    path('excluirPedido/<int:id>', views.excluirPedido, name="excluirPedido"),
    path('servico/', views.servico, name='servico'),
    path('editarServico/<int:id>/', views.editarServico, name='editarServico'),
    path('excluirServico/<int:id>/', views.excluirServico, name='excluirServico'),
    path('pagamento/', views.pagamento, name='pagamento'),
    path('editarPagamento/<int:id>/', views.editarPagamento, name='editarPagamento'),
    path('excluirPagamento/<int:id>/', views.excluirPagamento, name='excluirPagamento'),
    path('pet/', views.pet, name='pet'),
    path('editarPet/<int:id>/', views.editarPet, name='editarPet'),
    path('excluirPet/<int:id>/', views.excluirPet, name='excluirPet'),
    path('itemServico/', views.itemServico, name='itemServico'),
    path('editarItemServico/<int:id>/', views.editarItemServico, name='editarItemServico'),
    path('excluirItemServico/<int:id>/', views.excluirItemServico, name='excluirItemServico'),
    path('anexo/', views.anexo, name='anexo'),
    path('editarAnexo/<int:id>/', views.editarAnexo, name='editarAnexo'),
    path('excluirAnexo/<int:id>/', views.excluirAnexo, name='excluirAnexo'),
    path("login/", auth_views.LoginView.as_view(template_name="login.html"),name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="login"), name="logout"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projetoClinicaVeterinaria/ClinicaVeterinaria/app/models.py
from django.db import models
from django.utils import timezone
from django.db.models import Sum


# Create your models here.
class Clinica(models.Model):
    nome = models.CharField(max_length=100)
    CNPJ = models.CharField(max_length=20, unique=True)
    endereco = models.TextField()
    telefone = models.CharField(max_length=20)
    logo = models.ImageField(upload_to='logo/', null=True, blank=True)
    
    def __str__(self):
        return self.nome


class Veterinario(models.Model):
    nome = models.CharField(max_length=100)
    especialidade = models.CharField(max_length=100)
    telefone = models.CharField(max_length=20)
    idClinica = models.ForeignKey(Clinica, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.nome
 

class Cliente(models.Model):
    nome = models.CharField(max_length=50)
    telefone = models.CharField(max_length=20)
    email = models.EmailField(max_length=254, blank=True)
    endereco = models.TextField()
    idClinica = models.ForeignKey(Clinica, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.nome


class Pet(models.Model):
    nome = models.CharField(max_length=50)
    tipo = models.CharField(max_length=50)
    raca = models.CharField(max_length=50, blank=True)
    dataNascimento = models.DateField(auto_now=False, auto_now_add=False)
    sexo = models.CharField(max_length=50)
    idDono = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    imagemPet = models.ImageField(upload_to='imagemPet', null=True, blank=True)

    def __str__(self):
        return self.nome
    

class Servico(models.Model):
    tipo = models.CharField(max_length=100)
    descricao = models.TextField()
    valor = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'Ser. {self.id} - {self.tipo}'


class Pedido(models.Model):
    dataPedido = models.DateTimeField(auto_now_add=True)
    valorTotal = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    idCliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True)
    idPet = models.ForeignKey(Pet, on_delete=models.SET_NULL, null=True)
    idVeterinario = models.ForeignKey(Veterinario, on_delete=models.SET_NULL, null=True)
    anexos = models.BooleanField(null=True)

    def __str__(self):
        return f'Ped. {self.id} - Cli. {self.idCliente}'


class Anexos(models.Model):
    duracao = models.CharField(max_length=50)
    informacoes = models.TextField()
    idServico = models.ForeignKey(Servico, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'Anex. {self.id} - Serv. {self.idServico}'

class ItemServico(models.Model):
    qtd = models.IntegerField(default=1)
    subTotal = models.DecimalField(max_digits=10, decimal_places=2)
    idServico = models.ForeignKey(Servico, on_delete=models.SET_NULL, null=True)
    idPedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if self.idServico and self.qtd:
            self.subTotal = self.idServico.valor * self.qtd
        super().save(*args, **kwargs)
    
      # Atualiza o total do pedido
        if self.idPedido:
            total = ItemServico.objects.filter(idPedido=self.idPedido).aggregate(Sum('subTotal'))['subTotal__sum'] or 0
            self.idPedido.valorTotal = total
            self.idPedido.save(update_fields=['valorTotal'])

    def delete(self, *args, **kwargs):
        pedido = self.idPedido
        super().delete(*args, **kwargs)
        if pedido:
            total = ItemServico.objects.filter(idPedido=pedido).aggregate(Sum('subTotal'))['subTotal__sum'] or 0
            pedido.valorTotal = total
            pedido.save(update_fields=['valorTotal'])

    def __str__(self):
        return f'Item {self.id} - Ped. {self.idPedido}'

class Pagamento(models.Model):
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    formaPagamento = models.CharField(max_length=50)
    idPedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)

    def __str__(self):
        return f'Pag. {self.id} - Ped. {self.idPedido}'

projetoClinicaVeterinaria/ClinicaVeterinaria/app/templates/pagamento/editarPagamento.html
{% extends 'base.html' %}
{% load static %}


{%block estiloCss%}
<link rel="stylesheet" href="{%static 'css/padrao.css'%}">
{%endblock%}

{%block titulo%} 
Editar Pagamento
{%endblock%}

{% block conteudo %}
<div class="cont">
    <h1>Editar Pagamento</h1>
    <form method="POST">
        {% csrf_token %}
        <div>
            <label>VALOR</label>
            {{ formulario.valor }}
        </div>
        <div>
            <label>FORMA DE PAGAMENTO</label>
            {{ formulario.formaPagamento }}
        </div>
        <div>
            <label>PEDIDO</label>
            {{ formulario.idPedido }}
        </div>
        <button type="submit">SALVAR</button>
    </form>
</div>
{% endblock %}

projetoClinicaVeterinaria/ClinicaVeterinaria/app/templates/pagamento/excluirPagamento.html
{% extends 'base.html' %}
{% load static %}

{%block estiloCss%}
<link rel="stylesheet" href="{%static 'css/padrao.css'%}">
{%endblock%}

{%block titulo%} 
Excluir Pagamento
{%endblock%}

{% block conteudo %}
<div class="cont">
    <h1><strong>EXCLUIR PAGAMENTO</strong></h1>
    
    <p>Deseja excluir o pagamento de <strong>R$ {{ pagamento.valor }}</strong>?</p>
    <div>
        <p><strong>ID:</strong> {{ pagamento.id }}</p>
        <p><strong>VALOR:</strong> R$ {{ pagamento.valor }}</p>
        <p><strong>FORMA DE PAGAMENTO:</strong> {{ pagamento.formaPagamento }}</p>
        <p><strong>PEDIDO:</strong> {{ pagamento.idPedido.id }}</p>
    </div>

    <form method="POST">
        {% csrf_token %}
        <button type="submit">Confirmar Exclusão</button>
        <a class="btnA" href="{% url 'pagamento' %}">Cancelar</a>
    </form>
</div>
{% endblock %}

projetoClinicaVeterinaria/ClinicaVeterinaria/app/templates/pagamento/pagamento.html
{% extends 'base.html' %}
{% load static %}
{% load l10n %}


{% block estiloCss %}
<link rel="stylesheet" href="{% static 'css/padrao.css' %}">
{% endblock %}

{% block titulo %}
Pagamentos
{% endblock %}

{% block conteudo %}
<div>
    <h1>Pagamentos cadastrados</h1>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Valor</th>
                <th>Forma de Pagamento</th>
                <th>Pedido</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for pagamento in pagamentos %}
            <tr>
                <td>{{ pagamento.id }}</td>
                <td>R$ {{ pagamento.valor }}</td>
                <td>{{ pagamento.formaPagamento }}</td>
                <td>{{ pagamento.idPedido.id }}</td>
                <td id="link">
                    <a class="btnA" href="{% url 'editarPagamento' pagamento.id %}">EDITAR</a>
                    <a class="btnA" href="{% url 'excluirPagamento' pagamento.id %}">EXCLUIR</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5">Nenhum pagamento cadastrado no sistema</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Paginação -->
   <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
    {%if pagamentos.number == 1%}
    {# Primeira / Anterior #}
      <li class="page-item disabled">
        <a class="page-link" href="#">&laquo; Primeira &#40 {{pagamentos.number}} &#41 </a>
      </li>
      <li class="page-item disabled">
        <a class="page-link" href="#">Anterior</a>
      </li>
      {% else %}
        {# Primeira / Anterior #}
         <li class="page-item">
        <a class="page-link" href="{% url 'pagamento' %}?pc=1">&laquo; Primeira &#40 1 &#41 </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="{% url 'pagamento' %}?pc={{pagamentos.previous_page_number}}">Anterior &#40 {{pagamentos.previous_page_number}} &#41</a>
      </li>

      {% endif %}


    {# página atual (apenas exibindo o número, igual ao seu exemplo) #}
      <li class="page-item disabled">
        <a class="page-link" href="">{{pagamentos.number}}</a>
      </li>

      {%if pagamentos.paginator.num_pages == pagamentos.number%}
    {# Próxima / Última #}
      <li class="page-item disabled">
        <a class="page-link" href="#">Próxima </a>
      </li>
      <li class="page-item disabled">
        <a class="page-link" href="#">Última &#40 {{pagamentos.paginator.num_pages}} &#41&raquo;</a>
      </li>
    {%else%}
     <li class="page-item">
        <a class="page-link" href="{% url 'pagamento' %}?pc={{pagamentos.next_page_number}}">Próxima &#40 {{ pagamentos.next_page_number}}&#41</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="{%url 'pagamento'%}?pc={{pagamentos.paginator.num_pages}}">Última &#40 {{pagamentos.paginator.num_pages}} &#41 &raquo;</a>
      </li>

      {%endif%}
    </ul>
    </nav>

    <hr>

    <h1>Cadastrar novo pagamento</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="form-grupo">
            <label>Valor</label>
            {{ formulario.valor }}
        </div>
        <div class="form-grupo">
            <label>Forma de Pagamento</label>
            {{ formulario.formaPagamento }}
        </div>
        <div class="form-grupo">
            <label>Pedido</label>
           <select name="idPedido" id="id_idPedido" class="formulario">
                <option value="">Selecione...</option>
                {% for pedido in pedidos_abertos %}
                    <option value="{{ pedido.id }}" data-total="{{ pedido.valorTotal|unlocalize }}">
                        Pedido nº {{ pedido.id }} - {{ pedido.idCliente }} (Total: R$ {{ pedido.valorTotal }})
                    </option>
                {% endfor %}
            </select>
        </div>
        <button type="submit">SALVAR</button>
    </form>
    <script>
document.addEventListener("DOMContentLoaded", function() {
    const pedidoSelect = document.getElementById("id_idPedido");
    const valorInput = document.getElementById("id_valor");

    pedidoSelect.addEventListener("change", function() {
        const option = pedidoSelect.options[pedidoSelect.selectedIndex];
        const total = parseFloat(option.dataset.total) || 0;
        valorInput.value = total.toFixed(2); // mostra o valor total do pedido
    });
});
</script>
</div>
{% endblock %}